#!/bin/bash
# Quick test script for session expiration handling

echo "=== K2 Session Expiration Test ==="
echo ""
echo "This script helps you test the session expiration handling locally"
echo ""
echo "1. Starting server on http://localhost:3000"
echo "   Run this first: npm start"
echo ""
echo "2. Open browser and navigate to:"
echo "   http://localhost:3000/test/session-expiration"
echo ""
echo "3. Use the test page to:"
echo "   - Manually clear session cookies"
echo "   - Run automated tests"
echo "   - Verify proper error handling"
echo ""
echo "Expected Results:"
echo "✓ Session expiration shows 'Your session has expired. Redirecting to login...'"
echo "✓ After ~1.5 seconds, redirected to login page"
echo "✓ No raw JSON displayed to user"
echo "✓ Server returns 401/403 with JSON (not HTML)"
echo ""
echo "=== Test Locations ==="
echo ""
echo "Login Page:           http://localhost:3000/facilitator/login"
echo "Dashboard:            http://localhost:3000/facilitator/dashboard"
echo "Session Test Suite:   http://localhost:3000/test/session-expiration"
echo ""
echo "=== Key Files ==="
echo ""
echo "Client-side handler:  public/js/access.js (secureApiCall function)"
echo "Server middleware:    controllers/authController.js (requireSessionAccess, requireAuth)"
echo "Test UI:              public/session-expiration-test.html"
echo "Documentation:        SESSION_EXPIRATION_TEST.md"
echo ""
